### ISSUE TITLE
Do not use SKNode as target parameter

### ISSUE THREAD

**Issue by ghost** [craiggrummitt/SpriteKitEasingSwift#2]
In action method, `SKNode` target parameter is used to retrieve node property.  Thus chain actions cannot be done because `SKNode` properties change along actions.

In place, remove this parameter and replace it by the needed property. For example, for `scaleToWithNode`, as the needed property is `scale` use `initialScale:CGFloat` as parameter.

**Comment by craiggrummitt** [comment]
Again this is as is from the Obj C port, but I completely agree. I have left the old methods in for legacy for now, but have added a new method for each animation type , which requires `from` and `to` parameters rather than extracting the value from the node. Thanks for your suggestions!
https://github.com/craiggrummitt/SpriteKitEasingSwift/commit/1586a754a0fa000c7bf0f990127a735044b0286a

**Comment by ghost** [comment]
Ok, great!
